name=SimpleSensor
version=1.0.0
author=Tedprogrammer
maintainer=Tedprogrammer
sentence=Beginner analog sensor library for Arduino.
paragraph=Reads analog sensor values, stores calibration, and maps sensor output to a desired range.
category=Sensors
url=https://github.com/Tedprogrammer/sensor_lib
architectures=*
